#!/usr/bin/perl -w

use strict;
use Getopt::Long;
use Host::Apache;

print "\nApache management v.0.1\n";
print "more info at: http://host.simpleness.org\n\n";

my ( $help, $domain, $subdomain, $user );
GetOptions (
            "help"        => \$help,
            "domain=s"    => \$domain,
            "subdomain=s" => \$subdomain,
            "user=s"      => \$user,
        );

my @command = grep { /^(add|remove|check|info|list|reload)$/ } @ARGV;
die( &help_message ) if $help || !@command;

my $apache = new Host::Apache;

$_ = $command[0];

#add server
/^add$/ && do {
    $apache->add( { 'domain'=>$domain, 'subdomain'=>$subdomain, 'user'=>$user } );
};

/^remove$/ && do {
};

/^check$/ && do {
};

/^info$/ && do {
};

/^list$/ && do {
};

/^reload$/ && do {
    $apache->reload;
};

sub help_message {
<<EOF;
Usage:  $0 [command] [options]
Command line parameters:
    add     - add new server
    remove  - existing server
    check   - check if server exists
    info    - show info about server
    list    - list all servers
    reload  - apache reload
Options:
    -d  --domain     domain name (ex. example.com)
    -s  --subdomain  subdomain name (ex. mail)
    -u  --user       linux user name
Show this help:
    $0 --help
EOF
}
